# Generated by Django 5.1.4 on 2024-12-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20241229_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
    ]
