# Generated by Django 5.1.4 on 2024-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_vat_included_product_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pos_listing',
            field=models.BooleanField(default=False, verbose_name='List on POS'),
        ),
    ]
